name: ShellCheck GitHub Action Workflow
on:
  push:
    branches: 
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  shellcheck_github_action:
    runs-on: ubuntu-latest
    name: shellcheck_github_action
    steps:
      - name: Generate Semantic Version
        id: tag_version
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main,master
          dry_run: true
          create_annotated_tag: true
          append_to_pre_release_tag: ${{ steps.jira_issue_finder.outputs.jira_issue }}

      - name: Print Semantic Version
        id: tag_maker
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          new_version=${{ steps.tag_version.outputs.new_version }}
          new_tag=${{ steps.tag_version.outputs.new_tag }}
          echo "::set-output name=new_tag::${new_tag}"
          echo "::set-output name=new_version::${new_version}"
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      new_version: ${{ steps.tag_version.outputs.new_version }}
